### ISSUE TITLE
Can't find a way to inject a javascript on frames.

### ISSUE THREAD

**Issue by rankinmark** [wirepair/autogcd#11]
I need to inject javascript code in a frame and execute it. Not on loading the page but after it's loaded and at any moment. In CEF3 (Chromium Embedded Framework) it's possible. How it an be done?

**Comment by wirepair** [comment]
Hi @rankinmark. Unfortunately, this is going to require you to call out to gcd to get what you want. You need to capture the execution context id's as the scripts are parsed:
```Go
tab.Subscribe("Runtime.executionContextCreated", func(target *ChromeTarget, v []byte) {
		msg := &gcdapi.RuntimeExecutionContextCreatedEvent{}
		err := json.Unmarshal(v, msg)
		if err != nil {
			t.Fatalf("error unmarshalling event data: %v\n", err)
		}
                // check your frame url here, or just capture the msg.Params.Context.Id+url for later use
		if msg.Params.Context.Origin != testServerAddr[:len(testServerAddr)-1] {
			return
		}
		scriptSource := "document.location.href"
		objectGroup := "gcdtest"
		awaitPromise := false
		includeCommandLineAPI := true
		contextId := msg.Params.Context.Id // Note the context id being passed in for Runtime.Evaluate
		silent := true
		returnByValue := false
		generatePreview := true
		userGestures := true
		rro, exception, err := target.Runtime.Evaluate(scriptSource, objectGroup, includeCommandLineAPI, silent, contextId, returnByValue, generatePreview, userGestures, awaitPromise)
		if err != nil {
			t.Fatalf("error evaulating: %s %s\n", err, exception)
		}

		if val, ok := rro.Value.(string); ok {
			if val != testServerAddr {
				t.Fatalf("invalid location returned expected %s got %s\n", testServerAddr, val)
			}
		} else {
			t.Fatalf("error rro.Value was not a string")
		}
		close(doneCh)
	})
```

In the above gcd test case (https://github.com/wirepair/gcd/blob/master/gcd_test.go#L176) I'm immediately calling Runtime.Evaluate, but you probably just want to capture the context id + url in a sync map for later use.

This may be a nice feature to have to automatically capture context id's and urls per page load and have a tab.EvaluateScriptInFrame(script, frameUrl str) { ... }

**Comment by wirepair** [comment]
@rankinmark haven't heard from you for a while, please re-open if this does not work for you.

**Comment by rankinmark** [comment]
Your solution kinda works, but there are some problems. I can inject and execute js code in frames and get a result.
1) I use the first part of your solution to get all context ids of all frames and save them with their url. I don't consider contextids where there is no url. Then I use the second part target.Runtime.Evaluate iterating with every contextid I saved. Some times Evaluate can't find the contextid (why?) and gcd exit with panic.
So it's very unstable and I don't know how to solve this problem.
2)When I open more than one tab and launch the first part to collect contextid+url I get a lot more contextids even more than the sum of the frame sin the 3 pages I am testing. I don't know why.
I can provide my source code if you want.

**Comment by wirepair** [comment]
v8 will create a context for more than just documents/frames. (Eval, Function etc) will create an execution context, that's why filtering on the urls is probably what you want. Also they may 'disappear' if the context finishes executing and is destroyed, probably what you are seeing in some cases here. Without a simplified set of pages + test code I can't really help you out, if you have some I can take a look.

**Comment by rankinmark** [comment]
[chromegcd.zip](https://github.com/wirepair/autogcd/files/1194841/chromegcd.zip)

**Comment by wirepair** [comment]
Hello @rankinmark sorry for the late reply I was on vacation. I tested your code it seemed to work for me after I changed your log.Fatalf to log.Printf's in EvalFrame since an invalid context id isn't exactly fatal, they can come and go depending on what the browser is doing. As for the panic, I assume that is because you did not set a termination handler (default is to panic, which I should probably change to log...)
```Go
auto := autogcd.NewAutoGcd(settings) // create our automation debugger
auto.Start()                         // start it
terminationHandler := func(reason string) {
	log.Printf("terminated: %s\n", reason)
}
auto.SetTerminationHandler(terminationHandler)
defer auto.Shutdown()
```
