### ISSUE TITLE
how to get full dimensions of document element

### ISSUE THREAD

**Issue by kmanley** [wirepair/autogcd#13]
I tried to get the dimensions of the document element

```go
element, _ := tab.GetDocument()
dimensions, _ := element.Dimensions()
```

and it works, but it seems to return the box model constrained to the current viewport.

I would like to get the document height unconstrained. In other words, the total height of the page given the viewport width. Is there a way to do that?

Thanks.

**Comment by wirepair** [comment]
Hello @kmanley, I'm not entirely sure... did you look at calling gcdapi directly? There are some things of interest:
https://github.com/wirepair/gcd/blob/f4b496a606c33cf9690387e4417f4615b6cf6415/gcdapi/overlay.go
https://github.com/wirepair/gcd/blob/f4b496a606c33cf9690387e4417f4615b6cf6415/gcdapi/layertree.go
https://github.com/wirepair/gcd/blob/f4b496a606c33cf9690387e4417f4615b6cf6415/gcdapi/dom.go

To call gcd stuff directly:
```Go
doc := tab.GetDocument()
doc.NodeId()
tab.DOM.GetBoxModel(nodeId)
tab.Page.GetLayoutMetrics()```

The tab object has all API domains available as a nested structure. Let me know if you can find something that helps!

**Comment by wirepair** [comment]
buh i'm a dummy you need to get the body dimensions not the document:
```Go
func TestTabGetBodySize(t *testing.T) {
	var err error

	testAuto := testDefaultStartup(t)
	defer testAuto.Shutdown()

	tab, err := testAuto.NewTab()
	if err != nil {
		t.Fatalf("error getting tab")
	}
	//tab.Debug(true)
	if _, err := tab.Navigate(testServerAddr + "big_body.html"); err != nil {
		t.Fatalf("Error navigating: %s\n", err)
	}
	tab.WaitStable()

	bodies, err := tab.GetElementsBySelector("body")
	if err != nil {
		t.Fatalf("error getting body")
	}
	for _, body := range bodies {
		size_f, _ := body.Dimensions()
		t.Logf("body %#v\n", size_f)
	}

	doc, _ := tab.GetDocument()
	size_d, _ := doc.Dimensions()
	t.Logf("doc: %#v\n", size_d)
}
```
output:
```
        tab_test.go:150: body []float64{8, 8, 1664, 8, 1664, 3554, 8, 3554}
        tab_test.go:155: doc: []float64{0, 0, 1672, 0, 1672, 1297, 0, 1297}
```

**Comment by wirepair** [comment]
I'm going to go ahead and assume you want this so you can take a screen shot of the entire body. Right now autogcd just does the current viewport, i think you'll need to call gcdapi directly, passing in the Clip *PageViewport value using gcdapi.PageCaptureScreenshotParams struct: https://github.com/wirepair/gcd/blob/master/gcdapi/page.go#L896. So just look at how tab.GetScreenshot works and just call it directly with your own parameter values.

**Comment by kmanley** [comment]
Thanks @wirepair!
