### ISSUE TITLE
which version of Chromium does this work with?

### ISSUE THREAD

**Issue by kmanley** [wirepair/autogcd#17]
Please consider specifying which version of Chromium and/or headless_shell this works with, or bundle it with the project, similar to how the GoogleChrome/puppeteer project does.

**Comment by wirepair** [comment]
Where does puppeteer specify which version it works with? I don't see anything obvious on their github page.

**Comment by wirepair** [comment]
Ah it looks like it downloads a specific version of chromium. Might be worth having an option for that too, I accept pull requests!

**Comment by kmanley** [comment]
The puppeteer project specifies the version in https://github.com/GoogleChrome/puppeteer/blob/master/package.json
(see chromium_revision)
I'm just asking for that info to be specified somewhere in this project too, even if just in the README

**Comment by wirepair** [comment]
Looking into this a bit more, seems like they pull the branch info from https://omahaproxy.appspot.com/all.json. I think what makes the most sense is to have the gcd package use this as a basis for downloading the relevant protocol files from the 'stable' branch. Then creating a global in gcdapi for exporting the chromium revision number. That way from code you can look up what revision it is relevant for. Next time I go to update gcd I'll add this feature (probably this weekend).

**Comment by kmanley** [comment]
@wirepair that sounds great -- thx

**Comment by wirepair** [comment]
Hi @kmanley I ended up going with the dev channel as it supports more of the things I use it for. For now on all protocol updates will include the chrome dev version information.

**Comment by kmanley** [comment]
@wirepair nice one - thx
