### ISSUE TITLE
Just an idea - method to get all elements that match a xpath selector

### ISSUE THREAD

**Issue by patanasov** [wirepair/autogcd#19]
For a few days I have been learning and testing the library, but I noticed that perhaps there is a method that would be useful - method to get all elements that match a xpath selector. 

Here is my suggestion for extending **type Tab**:

```
func (t *Tab) GetElementsBySearch(selector string, includeUserAgentShadowDOM bool) ([]*Element, error) {
	id, count, err := t.DOM.PerformSearch(selector, includeUserAgentShadowDOM)
	if err != nil {
		return nil, err
	}

	if count < 1 {
		return make([]*Element, 0), nil
	}

        nodeIds, errQuery := t.DOM.GetSearchResults(id, 0, count)
	if errQuery != nil {
		return nil, errQuery
	}

	elements := make([]*Element, len(nodeIds))

	for k, nodeId := range nodeIds {
		elements[k], _ = t.GetElementByNodeId(nodeId)
	}

	return elements, nil
}
```

**Comment by wirepair** [comment]
Hey @patanasov thanks for the suggestion, I agree this looks useful. Would you be able to submit a PR with a simple unit test to verify it works?

**Comment by patanasov** [comment]
Thanks @wirepair. I will do my best to open a PR soon.

**Comment by wirepair** [comment]
Sorry @patanasov I was on vacation without a laptop, I just reviewed your PR, just two small requests, but other than that looks good!

**Comment by patanasov** [comment]
Hi @wirepair, do you want some changes to be made on my PR? Thanks :-)

**Comment by wirepair** [comment]
@patanasov yes please!

**Comment by wirepair** [comment]
Thank you for the PR!
