### ISSUE TITLE
Setting Headers

### ISSUE THREAD

**Issue by aPaleBlueDot** [wirepair/autogcd#22]
Hi, 

This is a question rather than an issue. A site I'm crawling with autogcd won't respond properly unless the request has headers. Not sure how to pass headers to my Tab. Is func (*Network).SetExtraHTTPHeaders(headers map[string]interface{}) (*ChromeResponse, error) in network.go the right way to do this?

Thx

**Comment by wirepair** [comment]
Hello @aPaleBlueDot yup you are correct, just remember to do tab.Network.Enable()
```go
tab.Network.Enable(-1, -1)
headers := make(map[string]interface{})
headers["test"] = "hi"
r, err := tab.Network.SetExtraHTTPHeaders(headers)
if err != nil {
	t.Fatalf("error setting headers: %s\n", err)
}
t.Logf("%#v\n", r)
if _, errorText, err := tab.Navigate("http://localhost:4445"); err != nil {
	t.Fatalf("Error navigating: %s %s\n", errorText, err)
}
```
