### ISSUE TITLE
RuntimeRemoteObject.value should be interface{} currently is a string

### ISSUE THREAD

**Issue by davyzhang** [wirepair/autogcd#9]
https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#type-RemoteObject

it will gives an error 
```json: cannot unmarshal object into Go struct field RuntimeRemoteObject.value of type string```

when the ret value is an object.

in api_overrides.go

```golang
	if err := json.Unmarshal(resp.Data, &chromeData); err != nil {
		return nil, nil, err
	}
```
try to decode resp.Data to RuntimeRemoteObject,

but RuntimeRemoteObject.Value is a string type

it should be map[string]interface{} or interface{} when the type is "object"

here is the sample response from my usecase:

```json
{  
   "id":5521,
   "result":{  
      "result":{  
         "type":"object",
         "value":{  
            "0":{  

            },
            "length":1,
            "context":{  
               "location":{  
                  "replace":{  

                  },
                  "assign":{  

                  },
                  "href":"https://x/",
                  "ancestorOrigins":{  

                  },
                  "origin":"https://x",
                  "protocol":"https:",
                  "host":"x",
                  "hostname":"x",
                  "port":"",
                  "pathname":"/",
                  "search":"",
                  "hash":"",
                  "reload":{  

                  }
               },
               "fb_xdm_frame_https":{  

               },
               "gtmHasFormSubmitListenerTag":true,
               "alttext-image":null,
               "_hjRemoteVarsFrame":{  

               }
            },
            "selector":"#search"
         }
      }
   }
}
```

**Comment by wirepair** [comment]
Good find, looks like this maybe a problem with the gcd package api generator. I'm not sure I account for the 'any' type when generating the APIs, I default to string if it's not found. I'll need to modify github.com/wirepair/gcd/gcdapigen to account for this. It may be a few days before I can get to this.

**Comment by wirepair** [comment]
Just a quick update, I'm still working on this, looks like there is a problem with treating it as a map[string]interface{} that i'm still trying to work through. Hopefully I can have something in the next few days. Of course I'm open to patches if you already have something.

**Comment by davyzhang** [comment]
Sorry for this, if it will take too much time. In my use case, I just ignored the returned err. How about treat the result as interface{} for now and leave the rest of work to the users. The value object in the document is optional(don't know why) and the type is various, even with subtypes. I don't think we need to track them all this time.

**Comment by wirepair** [comment]
Yeah I may have to go that route, looks like I had a few other bugs that this lead me to find & fix so definitely not a waste of time.

**Comment by wirepair** [comment]
hey @davyzhang I just updated gcdapigen to fix the issues and updated autogcd to reflect those changes. Can you verify it works now and allows you to convert to your requested object type? Close this ticket if confirmed, or signal to me that it works and I'll close it.

Thanks again for reporting this.

**Comment by davyzhang** [comment]
confirmed, thanx for your efforts
